#!/bin/sh
# Copyright (C) 2002-2005 Flavio Stanchina
# Copyright (C) 2005-2006 Aric Cyr
# Copyright (C) 2007 Mario Limonciello
# Copyright (C) 2007 Alberto Milone



PKGVER=`dpkg-query -W -f='${Version}' nwriemann | awk -F "-" '{print $1}'`
PKGVER=${PKGVER#*:}

SOURCES=/var/lib/dkms/nwriemann/
VERSION=173.15.13
STATUS=$(dpkg --compare-versions "$PKGVER" lt "$VERSION" && echo "True" || echo "False")

case "$1" in
	configure)
		# act only if the version of the current package is lower than $VERSION
		if [ "$STATUS" = "True" ] && [ -d $SOURCES ]; then
			echo "Cleaning up the DKMS tree"
			for directory in $(ls $SOURCES); do
				kind=$(echo "$directory" | awk '$1 ~ /.*[a-z].*$/ { print "alpha"; next } { print "num" }')
				# the names of the directories containing the version of the driver are digits (e.g. 177.70)
				if [ "$kind" = "num" ]; then
					comparison=$(echo "$directory" | awk -v Version="$PKGVER" '($1 != Version) { print "yes"; next } { print "no" }')
					# if the version is less than $VERSION
					if [ "$comparison" = "yes" ]; then
						rm -rf $SOURCES$directory 2>/dev/null
					fi
				fi
			done
			echo "Done."
		fi
		
		echo "Removing all DKMS Modules"
		dkms remove -m nwriemann -v $PKGVER --all -q > /dev/null
		echo "Done."
		echo "Adding Module to DKMS build system"
		echo "driver version= $PKGVER"
		dkms add -m nwriemann -v $PKGVER > /dev/null
		echo "Doing initial module build"
		dkms build -m nwriemann -v $PKGVER > /dev/null
		echo "Installing initial module"
		dkms install -m nwriemann -v $PKGVER > /dev/null
		echo "Done."
	;;
esac


