#!/bin/sh

# When udevtrigger actions the local filesystems are not neccesarily
# ready, so we re-trigger our load_riemann.sh udev event

# make sure load_riemann.sh is called
if [ -e /sbin/udevadm ]
then
	# opensuse does not have udevadm in the default path
	/sbin/udevadm trigger --action=change
else
	udevadm trigger --action=change
fi
